version: "3.7"
services:
  nodejs:
    build:
      context: ./
      dockerfile: docker/nodejs/Dockerfile
    hostname: nodejsserver
    ports:
      - "80:8888" 
    networks:
      - project_network

  nginx:
    image: nginx:alpine
    hostname: project.localhost
    tty: true
    ports:
      - "81:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - nodejs
    networks:
      - project_network
      
networks:
  project_network:
    driver : bridge 
